### ISSUE TITLE
pip install fails on clean virtualenv - h5py related?

### ISSUE THREAD

**Issue by tseemann** [LUMC/kPAL#1]
```
% virtualenv /bio/sw/kPAL
% /bio/sw/kPAL/bin/pip install kPAL
```

<snip>

Command /bio/sw/kPAL/bin/python -c "import setuptools;**file**='/bio/sw/kPAL/build/h5py/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-53rtkL-record/install-record.txt --install-headers /bio/sw/kPAL/include/site/python2.7 failed with error code 1 in /bio/sw/kPAL/build/h5py

Exception information:
Traceback (most recent call last):
  File "/bio/sw/kPAL/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/bio/sw/kPAL/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 250, in run
    requirement_set.install(install_options, global_options)
  File "/bio/sw/kPAL/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1133, in install
    requirement.install(install_options, global_options)
  File "/bio/sw/kPAL/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 577, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/bio/sw/kPAL/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /bio/sw/kPAL/bin/python -c "import setuptools;**file**='/bio/sw/kPAL/build/h5py/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-53rtkL-record/install-record.txt --install-headers /bio/sw/kPAL/include/site/python2.7 failed with error code 1 in /bio/sw/kPAL/build/h5py

**Comment by martijnvermaat** [comment]
Actually, Cython is listed as a dependency in h5py's `setup.py`, but I have no idea why it isn't installed first (there also have been quite some changes there with h5py release 2.4.0).

I opened bug h5py/h5py#535

**Comment by tseemann** [comment]
Thanks for looking into it.  I'm not sure I'll ever fully understand Python packaging either!
