### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sterding** [LUMC/kPAL#8]
hi, 

I got the following error when upgrading to the latest version of kPal. I'm a newbie of python. It seems related with cython. Could you please help?

[xd010@eris1n2 ~]$ pip install --install-option="--install-dir=/PHShome/xd010/lib/python2.7/site-packages/" --upgrade kPal
Requirement already up-to-date: kPal in ./lib/python2.7/site-packages
Requirement already up-to-date: numpy in ./lib/python2.7/site-packages (from kPal)
Requirement already up-to-date: h5py>=2.1 in ./lib/python2.7/site-packages (from kPal)
Requirement already up-to-date: biopython in ./lib/python2.7/site-packages (from kPal)
Requirement already up-to-date: semantic-version in ./lib/python2.7/site-packages (from kPal)
Requirement already up-to-date: future in ./lib/python2.7/site-packages (from kPal)
Downloading/unpacking Cython>=0.17 from https://pypi.python.org/packages/source/C/Cython/Cython-0.23.4.tar.gz#md5=157df1f69bcec6b56fd97e0f2e057f6e (from h5py>=2.1->kPal)
  Downloading Cython-0.23.4.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip_build_xd010/Cython/setup.py) egg_info for package Cython
    Unable to find pgen, not compiling formal grammar.
    
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
Requirement already up-to-date: six in ./lib/python2.7/site-packages (from h5py>=2.1->kPal)
Installing collected packages: Cython
  Found existing installation: Cython 0.21
    Uninstalling Cython:
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/PHShome/xd010/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/PHShome/xd010/lib/python2.7/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/PHShome/xd010/lib/python2.7/site-packages/pip/req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "/PHShome/xd010/lib/python2.7/site-packages/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/PHShome/xd010/lib/python2.7/site-packages/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/PHShome/xd010/lib/python2.7/site-packages/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/PHShome/xd010/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/PHShome/xd010/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/PHShome/xd010/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/PHShome/xd010/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/PHShome/xd010/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/PHShome/xd010/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/apps/source/python-lib/python2.7/cython/0.21/lib/python2.7/site-packages/Cython-0.21-py2.7-linux-x86_64.egg/Cython/Build/Tests/TestInline.py'

Storing debug log for failure in /PHShome/xd010/.pip/pip.log

-Xianjun

**Comment by martijnvermaat** [comment]
Hi @sterding,

I'm not sure what's going on here, but it looks like something specific to
your Python setup.

Although you're trying to install packages in your homedir, apparently Cython
is already system-wide
(`/apps/source/python-lib/python2.7/cython/0.21/lib/python2.7/site-packages`). Since
one of our dependencies needs a newer Cython version, it tries to uninstall
that one but you don't have permissions to touch the system-wide Cython
package.

As an alternative, you could try installing in a
[Virtual Environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/),
isolated from the system Python packages. E.g,:

```
virtualenv kpal
source kpal/bin/activate
pip install kpal
```
